apiVersion: v1
kind: Service
metadata:
  name: sopranobot-service
  labels:
    app: sopranobot
  annotations:
    cloud.google.com/backend-config: '{"default": "soprano-backend-config"}'
spec:
  type: NodePort
  selector:
    app: sopranobot
  ports:
    - protocol: TCP
      name: http
      port: 80        # The port the Ingress will talk to
      targetPort: 8000 # The port your FastAPI code listens on